export const PRODUCT_RANKING_LABEL = {
    TOP: 'TOP',
    GOLD: 'GOLD',
    BRONZE: 'BRONZE',
    SILVER: 'SILVER'
};

export const MY_PAGE_OPTIONS = {
    PROFILE: 'PROFILE',
    ORDER_AND_SHIPPING: 'ORDER_AND_SHIPPING',
    EXCEL_MASS_ORDER: 'EXCEL_MASS_ORDER',
    OUT_OF_STOCK_AND_RESTOCKED: 'OUT_OF_STOCK_AND_RESTOCKED',
    SESSION_AND_SERVICE: 'SESSION_AND_SERVICE',
    INVOICE: 'INVOICE',
    PRODUCT_DB_DOWNLOAD: 'PRODUCT_DB_DOWNLOAD',
    NOTICE: 'NOTICE',
    T_MONEY: 'T_MONEY',
    TCS_BOARD: 'TCS_BOARD'
};
